<a href="https://colab.research.google.com/github/Romneasek/Data_processing_Assignment/blob/main/Data_processing_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd

In [40]:
# 1) Generate an array of zeroes using inbuilt numpy function.

a = np.zeros((3,3))
b = np.zeros(6)
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0.]


In [41]:
# 2) Run the given code and find the dot product of both arrays.

import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[4 4 6 3]
 [5 9 6 4]
 [3 5 3 2]]
[[2 9 5]
 [5 8 5]
 [4 6 5]
 [3 4 7]]


In [42]:
a.dot(b)

array([[ 61, 116,  91],
       [ 91, 169, 128],
       [ 49,  93,  69]])

In [43]:
b.dot(a)

array([[ 68, 114,  81,  52],
       [ 75, 117,  93,  57],
       [ 61,  95,  75,  46],
       [ 53,  83,  63,  39]])

In [44]:
np.dot(a,b)

array([[ 61, 116,  91],
       [ 91, 169, 128],
       [ 49,  93,  69]])

In [45]:
# 3)Read the csv file provided using pandas and display the first 5 entries

data = pd.read_csv('/content/data.csv')
data.head(5)

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [46]:
# 4)Describe the data with all features.

data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [47]:
# 5)Find the total count of missing values for each feature.

data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [48]:
# 6)Display all the unique values from the 'DESCRIPTION’ column.

data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [49]:
# 7)Create a grouped table using 'DESCRIPTION' as the grouping columns with the means of all the other columns.

data.groupby('DESCRIPTION')['OBJECTID', 'ACRES', 'SHAPE.AREA', 'SHAPE.LEN'].mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [50]:
# 8)Generate a random sample of 10 rows from the data.

data.sample(10)

OBJECTID                            UNIT_NAME            DESCRIPTION  \
24        42  Pelican Point State Recreation Area  State Recreation Area   
8         29  Lewis and Clark Interpretive Center    Interpretive Center   
16        37           Elkhorn State Natural Area     State Natural Area   
1         22               Beaver Lake State Park             State Park   
14        33              Turtle River State Park             State Park   
5         26                 Icelandic State Park             State Park   
6         27            Lake Metigoshe State Park             State Park   
2         23      Fort Abraham Lincoln State Park             State Park   
7         28           Lewis and Clark State Park             State Park   
3         24               Fort Ransom State Park             State Park   

      ACRES  SHAPE.AREA  SHAPE.LEN  
24    25.22    0.000013   0.026357  
8     14.71    0.000007   0.016774  
16   264.84    0.000127   0.067082  
1    273.16    0.000129   0.080067  
14   775.28    0.000378   0.145220  
5    930.30    0.000461   0.166712  
6   1508.53    0.000751   0.212196  
2    836.47    0.000399   0.119868  
7    524.81    0.000256   0.130420  
3    933.78    0.000444   0.128733

In [51]:
# 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

data['New_feature'] = np.random.rand(25)

In [52]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.884750  
1   0.080067     0.298006  
2   0.119868     0.107773  
3   0.128733     0.016871  
4   0.125546     0.801208

In [53]:
# 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [54]:
data["OBJECTID"].isnull().sum()

0

In [55]:
data["OBJECTID"] = data["OBJECTID"].replace(0, data["OBJECTID"].mean())

In [56]:
data["OBJECTID"]

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64